import { headers } from "next/headers";
import "../../styles/globals.css";
import styles from "../../styles/Home.module.css";
import { ReactNode } from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getData() {
  const subdomain = headers().get("subdomain")?.split(".")[0];
  metadata.title = "Welcome to " + subdomain;
  return { subdomain };
}

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}): JSX.Element {
  getData();

  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <div className={styles.main}>{children}</div>
        </div>
      </body>
    </html>
  );
}
